### ISSUE TITLE
Why does Terminal::Getpass die on ^C?

### ISSUE THREAD

**Issue by jjatria** [titsuki/raku-Terminal-Getpass#10]
Using `prompt` the user can cancel a prompt with Ctrl+C:

```
$ raku -e 'say prompt("Password: ")'
Password: ^C
$
```

But using `getpass` this results in an exception being thrown:

```
$ raku -MTerminal::Getpass -e 'say getpass'
Password: Died
  in block  at ... (Terminal::Getpass) line 30
  in sub unix-getpass at ... (Terminal::Getpass) line 24
  in sub getpass at ... (Terminal::Getpass) line 8
  in block <unit> at -e line 1
$
```

It's not uncommon for a user to Ctrl+C away from an unexpected password prompt, so this seemed to me to be a bug worth fixing. However this seems to have been intentionally introduced in a4573e484aab101da5fcf7de1959bfd8371f0d27. What's the rationale behind this?

**Comment by titsuki** [comment]
@jjatria Thanks for your comment!
As you mentioned, it seems better that `getpass` behaves consistently as `prompt` does.
I'll fix it sometime soon.

**Comment by titsuki** [comment]
> What's the rationale behind this?

Honestly to say, there aren't any rationales.
I undeliberately called `die` as a one of the ways of breaking a loop.
